import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {NavbarComponent} from "@/components/navbar";
import {FooterComponent} from "@/components/footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={'max-w-screen-lg mx-auto   '}  >
      <div className={'flex flex-col min-h-screen'}>
        <NavbarComponent/>
        <div className={'flex-grow flex flex-col '}>{children}</div>
        <FooterComponent/>
      </div></body>
    </html>
  )
}
